# Simplified package loading function for analysis scripts
# Generated by install_dependencies.R

load_packages <- function(packages) {
  for(pkg in packages) {
    if(!require(pkg, character.only = TRUE, quietly = TRUE)) {
      stop(paste('Package', pkg, 'not found. Please run install_dependencies.R first.'))
    }
  }
}
