#!/usr/bin/env Rscript

# Global Dependency Management for Blood Proteomics Analysis Project
# Author: Data Analysis Pipeline
# Description: Installs all required R packages for the entire project

# Set CRAN mirror for consistent package installation
if(is.null(getOption("repos")) || getOption("repos")["CRAN"] == "@CRAN@") {
  options(repos = c(CRAN = "https://cloud.r-project.org/"))
}

# Function to install packages if not available
install_if_missing <- function(packages) {
  for(pkg in packages) {
    if(!require(pkg, character.only = TRUE, quietly = TRUE)) {
      message(paste("Installing", pkg, "..."))
      install.packages(pkg, dependencies = TRUE)
      if(!require(pkg, character.only = TRUE, quietly = TRUE)) {
        stop(paste("Failed to install package:", pkg))
      } else {
        message(paste("✓", pkg, "installed successfully"))
      }
    } else {
      message(paste("✓", pkg, "already installed"))
    }
  }
}

# Comprehensive list of all packages used in the project
cat("Blood Proteomics Analysis - Installing Dependencies\n")
cat("==================================================\n\n")

# Core data manipulation packages
data_packages <- c("dplyr", "tidyr", "readr", "stringr")
cat("Installing data manipulation packages...\n")
install_if_missing(data_packages)

# Visualization packages
viz_packages <- c("ggplot2", "ggridges", "ggbeeswarm", "viridis", "scales", 
                  "gridExtra", "grid", "RColorBrewer")
cat("\nInstalling visualization packages...\n")
install_if_missing(viz_packages)

# Specialized analysis packages
analysis_packages <- c("UpSetR", "VennDiagram", "pheatmap", "corrplot")
cat("\nInstalling specialized analysis packages...\n")
install_if_missing(analysis_packages)

# Biological annotation packages (Bioconductor)
cat("\nChecking Bioconductor packages...\n")
if (!requireNamespace("BiocManager", quietly = TRUE)) {
  message("Installing BiocManager...")
  install.packages("BiocManager")
}

# Try to install Bioconductor packages with error handling
bioc_packages <- c("biomaRt", "org.Hs.eg.db", "GO.db", "KEGG.db")
for(pkg in bioc_packages) {
  if(!require(pkg, character.only = TRUE, quietly = TRUE)) {
    message(paste("Installing Bioconductor package", pkg, "..."))
    tryCatch({
      BiocManager::install(pkg, dependencies = TRUE, update = FALSE)
      if(require(pkg, character.only = TRUE, quietly = TRUE)) {
        message(paste("✓", pkg, "installed successfully"))
      } else {
        warning(paste("Failed to load", pkg, "after installation"))
      }
    }, error = function(e) {
      warning(paste("Failed to install Bioconductor package", pkg, ":", e$message))
    })
  } else {
    message(paste("✓", pkg, "already installed"))
  }
}

# Optional packages for enhanced functionality
optional_packages <- c("plotly", "DT", "knitr", "rmarkdown")
cat("\nInstalling optional packages...\n")
for(pkg in optional_packages) {
  tryCatch({
    install_if_missing(pkg)
  }, error = function(e) {
    warning(paste("Optional package", pkg, "failed to install:", e$message))
  })
}

# Print summary
cat("\n" , rep("=", 60), "\n")
cat("DEPENDENCY INSTALLATION SUMMARY\n")
cat(rep("=", 60), "\n")

# Check all packages
all_packages <- c(data_packages, viz_packages, analysis_packages, 
                 bioc_packages, optional_packages)

installed_count <- 0
failed_packages <- character()

for(pkg in all_packages) {
  if(require(pkg, character.only = TRUE, quietly = TRUE)) {
    installed_count <- installed_count + 1
  } else {
    failed_packages <- c(failed_packages, pkg)
  }
}

cat("Total packages checked:", length(all_packages), "\n")
cat("Successfully installed:", installed_count, "\n")
cat("Failed installations:", length(failed_packages), "\n")

if(length(failed_packages) > 0) {
  cat("\nFailed packages:\n")
  for(pkg in failed_packages) {
    cat("  ×", pkg, "\n")
  }
  cat("\nNote: Some packages may be optional and not critical for basic functionality.\n")
} else {
  cat("\n🎉 All packages installed successfully!\n")
}

cat("\nYou can now run any analysis script in the project.\n")
cat("Individual scripts will load packages as needed.\n")

# Create a simple package loading function for other scripts
cat("\nCreating package loader function...\n")
sink("load_packages.R")
cat("# Simplified package loading function for analysis scripts\n")
cat("# Generated by install_dependencies.R\n\n")
cat("load_packages <- function(packages) {\n")
cat("  for(pkg in packages) {\n")
cat("    if(!require(pkg, character.only = TRUE, quietly = TRUE)) {\n")
cat("      stop(paste('Package', pkg, 'not found. Please run install_dependencies.R first.'))\n")
cat("    }\n")
cat("  }\n")
cat("}\n")
sink()

message("✓ Created load_packages.R for use in analysis scripts")
message("\nDependency installation completed!")
message("Run 'source(\"load_packages.R\")' in analysis scripts to load required packages.") 